version: '2.4'

services:
  app:
    build:
      context: .
      target: base
    command: >-
      bash -c "yarn run typeorm migration:run &&
      yarn run start:dev"
    image: medguia/backend
    env_file: .env
    networks:
      - net
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - ./:/app:delegated
    depends_on:
      - db

  db:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
    networks:
      - net

volumes:
  db:

networks:
  net:
